---
applications:
- name: flux-JDT-service-provider
  memory: 1024M
  instances: 1
  no-route: true
  path: org.eclipse.flux.jdt.service.provider-0.0.1-SNAPSHOT-jar-with-dependencies.jar
  env:
    FLUX_HOST: https://flux.cfapps.io:4443
    FLUX_ADMIN_ID: \$super\$
    FLUX_ADMIN_TOKEN: <SECRET>
    FLUX_CF_CONTROLLER_URL: http://api.run.pivotal.io
    FLUX_CF_USER_ID: <CF user ID>
    FLUX_CF_PASSWORD: <CF user passworf>
    FLUX_CF_SPACE: flux
    FLUX_CF_ORG: FrameworksAndRuntimes
    FLUX_SERVICE_APP_ID: flux-JDT
    FLUX_SERVICE_POOL_SIZE: 3
    FLUX_SERVICE_MAX_INSTANCES: 50
